### ISSUE TITLE
EIC widget visualization enhancements

### ISSUE THREAD

**Issue by PMSeitzer** [eugenemel/maven#222]
For direct infusion type, customization around scan types.

**Comment by PMSeitzer** [comment]
First step: be able to apply a filter on MS1 scan.

**Comment by PMSeitzer** [comment]
MS1 filter successfully applied as of bfa6becaf7162aef99b7cf4a8c05f6165f7baa1c

**Comment by PMSeitzer** [comment]
child case: #223

**Comment by PMSeitzer** [comment]
Add ability to show/hide raw EICs (to make spline more visible)

**Comment by PMSeitzer** [comment]
As a first step, use the `_showSpline` variable to both show the spline and hide the raw intensities.  This does disallow viewing the spline and raw intensities at the same time, but it isn't easy to see much with both plotted at the same time anyway.

**Comment by PMSeitzer** [comment]
`_showSpline` retrieves the spline based on the smoothing algorithm, but does some additional processing (computes a cubic spline).  The option `show EICs as Lines` in combination with `show Spline` achieves the desired effect.  However, the spline that is shown is not the smoothed peaks that are used in peak grouping. This feature / issues should be carefully evaluated before restructuring, with input from users. Holding off on any changes in right click menu options for now.

**Comment by PMSeitzer** [comment]
When a filter is being applied to the EIC widget, it would be nice for this information to be displayed near the widget.  Ideally, it would be nice to be able to click on the information and remove the filter.

**Comment by PMSeitzer** [comment]
Here is a concrete list of steps to take:

- [ ] When a filter is applied to an EIC widget, display this information somewhere close to the widget, making it easy to click and remove this filter
- [ ] Certain right-click options should be factored out into button-click options, where if the button is pressed, the background is yellow, and if not pressed, not yellow.  The right-click options should also remain.  Some of the lesser-used EIC widget options can be removed for this purpose (history, mark peak as good, etc)
- [ ] Update visualizations surrounding splines

**Comment by PMSeitzer** [comment]
showing peak groups via isotopes is should be implemented (related to #380), and Showing peak groups should also be a button, which should be turned on by default.

**Comment by PMSeitzer** [comment]
Completed as of 7f816fd1b976b92518e19dd6db3bc07cdfe54347
